#--- indicates the starting of yml file.
---
- name: Playbook
#hostname defined in inventory file
  hosts: dev-servers 
#to perform tasks as a ubuntu user in remote server  
  remote_user: ubuntu 
  vars:
#path of the ssh key 
    ansible_ssh_private_key_file: "/Users/nthakuri/Downloads/postgres.pem"
  tasks:
    - name: Set authorized key in alternate location
      authorized_key:
        user: ubuntu
        state: absent
        key: "{{ lookup('file', '/Users/nthakuri/Downloads/id_rsa.pub') }}"
#whether this module should manage the directory of the authorized key file.
        manage_dir: False
        
